
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author porta
 */
public class Loggin extends javax.swing.JFrame {
    

     
    /**
     * Creates new form Loggin
     */
    public Loggin() {
        initComponents();
        this.setTitle("LOGIN UACM");
        this.setBackground(Color.RED);
        this.getContentPane().setBackground(Color.GRAY);
          
        ImageIcon aux= new ImageIcon(getClass().getResource("/img/logo_.png"));
        ImageIcon logo= new ImageIcon(aux.getImage().getScaledInstance(jLabel4.getHeight(), jLabel4.getWidth(), Image.SCALE_DEFAULT));
        jLabel4.setIcon(logo);
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_prof = new javax.swing.JButton();
        btnestudiante = new javax.swing.JButton();
        txtpwd = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usuario:");

        jLabel2.setText("Contraseña:");

        jLabel3.setText("Universidad Autonoma de la Ciudad de México");

        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btn_prof.setLabel("Profesor Iniciar sesion");
        btn_prof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_profActionPerformed(evt);
            }
        });

        btnestudiante.setText("Alumno Iniciar sesión");
        btnestudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnestudianteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btn_prof)
                        .addGap(99, 99, 99)
                        .addComponent(btnestudiante))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtpwd)
                            .addComponent(txtname, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))))
                .addContainerGap(129, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addComponent(jLabel2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_prof)
                    .addComponent(btnestudiante))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_profActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_profActionPerformed
        // TODO add your handling code here:
        
      
     if(txtname.getText().equals("julian.perez") &&  txtpwd.getText().equals("111")){
             JOptionPane.showMessageDialog(this, "Bienvenido profesor " + txtname.getText());
               LogginProfesor aux= new LogginProfesor();
               aux.setVisible(true);
               aux.setDatos("julian.perez", "3535", "julian.perez@alumno.uacm.edu.mx", 54, "Sociales");
               super.dispose();
         }else if (txtname.getText().equals("") || txtpwd.getText().equals("")){
             if(txtname.getText().equals("")){
                 JOptionPane.showMessageDialog(this, "Ingresa un usuario"+ txtname.getText() );
             }else{
                 JOptionPane.showMessageDialog(this, "Ingresa una contraseña"+txtpwd.getText() );
             }
         }else{
             JOptionPane.showMessageDialog(this, "Usuario y/o contraseña incorrectos "+ txtname.getText() + txtpwd.getText() );
         }
     
         
        
    }//GEN-LAST:event_btn_profActionPerformed

    private void btnestudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnestudianteActionPerformed
        // TODO add your handling code here:
        
      
         if(txtname.getText().equals("roberto.lopez") &&  txtpwd.getText().equals("1234")){
             JOptionPane.showMessageDialog(this, "Bienvenido alumno " + txtname.getText());
               LogginEstudiantes aux= new LogginEstudiantes();
               aux.setVisible(true);
               aux.setDatos("Roberto Lopez" ,"roberto.lopez@alumno.uacm.edu.mx", "34324", "Sociales");
               super.dispose();
         }else if (txtname.getText().equals("") || txtpwd.getText().equals("")){
             if(txtname.getText().equals("")){
                 JOptionPane.showMessageDialog(this, "Ingresa un usuario" );
             }else{
                 JOptionPane.showMessageDialog(this, "Ingresa una contraseña" );
             }
         }else{
             JOptionPane.showMessageDialog(this, "Usuario y/o contraseña incorrectos "+ txtname.getText() );
         }
    }//GEN-LAST:event_btnestudianteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loggin().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_prof;
    private javax.swing.JButton btnestudiante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpwd;
    // End of variables declaration//GEN-END:variables

    
}
